blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/orgs/IndionicHost/discussions/categories/feature-request
    about: Request for specific features/content addition here.
  - name: Discord community
    url: https://indionichost.com/discord
    about: Join our Discord support server.